DROP DATABASE IF EXISTS queryoverheadtest;
CREATE DATABASE queryoverheadtest;

\c queryoverheadtest

-- DROP TABLE IF EXISTS A CASCADE ;
-- DROP TABLE IF EXISTS B CASCADE ;
-- DROP TABLE IF EXISTS NM_AB CASCADE ;

CREATE TABLE A (ID BIGSERIAL PRIMARY KEY , NAME TEXT);
CREATE TABLE B (ID BIGSERIAL PRIMARY KEY , NAME TEXT);
CREATE TABLE NM_AB (
	ORDERING BIGSERIAL,
	SRCID    BIGINT NOT NULL REFERENCES A (ID) ON DELETE CASCADE,
	DSTID    BIGINT NOT NULL UNIQUE REFERENCES B (ID) ON DELETE CASCADE
);

INSERT INTO A (NAME) VALUES ('A1');
INSERT INTO B (NAME) VALUES ('B1');

INSERT INTO A (NAME) VALUES ('A2');
INSERT INTO B (NAME) VALUES ('B2');
INSERT INTO B (NAME) VALUES ('B3');
INSERT INTO B (NAME) VALUES ('B4');

INSERT INTO NM_AB (SRCID, DSTID) VALUES (1,1), (2,2), (2,3), (2,4);


SELECT ID, NAME FROM A;
SELECT ID, NAME FROM B;

SELECT NA.SRCID, NA.DSTID, B.NAME
FROM B INNER JOIN NM_AB NA ON B.ID = NA.DSTID;

GRANT ALL ON ALL TABLES IN SCHEMA public TO PUBLIC;